import type { Metadata } from "next";
import {
  DM_Sans,
  Inter,
  Merriweather,
  Nunito,
  Outfit,
  PT_Sans,
  Playfair_Display,
  Sen,
  Ubuntu,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const font = Outfit({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen, antialiased grainy", font.className)}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
